[package]
name = "xmb_lib"
version = "0.1.0"
authors = ["ScanMountGoat <>"]
edition = "2018"

[dependencies]
binread = "2.1.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
xmltree = "0.10.3"