[package]
name = "xmb"
version = "0.1.0"
authors = ["ScanMountGoat"]
edition = "2021"

[dependencies]
xmb_lib = { path = "../xmb_lib" }
xmltree = { version = "0.10.3", features = ["attribute-order"] }
clap = { version = "4.5.1", features = ["derive"] }