[package]
name = "xmb_lib"
version = "0.1.0"
authors = ["ScanMountGoat"]
edition = "2021"

[dependencies]
binrw = "0.8.4"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"], optional = true }
arbitrary = { version = "1.0", features = ["derive"], optional = true }
xmltree = { version = "0.10.3", features = ["attribute-order"] }
indexmap = { version = "1.7.0" }
ssbh_lib = { git = "https://github.com/ultimate-research/ssbh_lib" }
ssbh_write = { git = "https://github.com/ultimate-research/ssbh_lib" }

[features]
arbitrary = ["dep:arbitrary", "ssbh_lib/arbitrary"]
serde = ["dep:serde", "ssbh_lib/serde", "indexmap/serde"]