[package]
name = "xmb_lib"
version = "0.1.0"
authors = ["ScanMountGoat <>"]
edition = "2018"

[dependencies]
binread = "2.1.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
xmltree = { version = "0.10.3", features = ["attribute-order"] }
indexmap = { version = "1.7.0", features = ["serde"] }
ssbh_lib = { git = "https://github.com/ultimate-research/ssbh_lib" }
ssbh_write = { git = "https://github.com/ultimate-research/ssbh_lib" }